var Cake = require('../models/Cake');
var keys = require('../config/keys');
var mongoose = require('mongoose');

mongoose.connect(keys.mongodb.dbURI);

var cakes = [
    //vivek sovani cakes
    // Black forest cakes//
    new Cake({
        cakeId: 'bf002',
        name: 'Black forest',
        brandId : 'vsnnsk',
        category: 'bf',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 360,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 360,
    }),
    new Cake({
        cakeId: 'bf004',
        name: 'Black forest',
        brandId : 'vsnnsk',
        category: 'bf',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 360,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 360,
    }),
    new Cake({
        cakeId: 'bf005',
        name: 'Black forest',
        brandId : 'vsnnsk',
        category: 'bf',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 360,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 360,
    }),
    new Cake({
        cakeId: 'bf008',
        name: 'Black forest',
        brandId : 'vsnnsk',    
        category: 'bf',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 360,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 360,
    }),
    new Cake({
        cakeId: 'bf011',
        name: 'Black forest',
        brandId : 'vsnnsk',
        category: 'bf',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 380,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 380,
    }),
    new Cake({
        cakeId: 'bf013',
        name: 'Black forest',
        brandId : 'vsnnsk',
        category: 'bf',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 360,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 360,
    }),
    new Cake({
        cakeId: 'bf015',
        name: 'Black forest',
        brandId : 'vsnnsk',
        category: 'bf',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 380,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 380,
    }),
    new Cake({
        cakeId: 'bf016',
        name: 'Black forest',
        brandId : 'vsnnsk',
        category: 'bf',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 360,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 360,
    }),
    new Cake({
        cakeId: 'bf017',
        name: 'Black forest',
        brandId : 'vsnnsk',
        category: 'bf',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 360,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 360,
    }),
    // Buttercotch cakes//
    new Cake({
        cakeId: 'bs001',
        name: 'ButterScotch',
        brandId : 'vsnnsk',
        category: 'bs',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 360,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 360,
    }),
    new Cake({
        cakeId: 'bs002',
        name: 'ButterScotch',
        brandId : 'vsnnsk',
        category: 'bs',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 380,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 380,
    }),
    new Cake({
        cakeId: 'bs003',
        name: 'ButterScotch',
        brandId : 'vsnnsk',
        category: 'bs',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 370,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 370,
    }),
    new Cake({
        cakeId: 'bs005',
        name: 'ButterScotch',
        brandId : 'vsnnsk',
        category: 'bs',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 370,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 370,
    }),
    new Cake({
        cakeId: 'bs006',
        name: 'ButterScotch',
        brandId : 'vsnnsk',
        category: 'bs',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 380,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 380,
    }),
    new Cake({
        cakeId: 'bs007',
        name: 'ButterScotch',
        brandId : 'vsnnsk',
        category: 'bs',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 370,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 370,
    }),
    new Cake({
        cakeId: 'bs008',
        name: 'ButterScotch',
        brandId : 'vsnnsk',
        category: 'bs',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 370,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 370,
    }),
    new Cake({
        cakeId: 'bs009',
        name: 'ButterScotch',
        brandId : 'vsnnsk',
        category: 'bs',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 370,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 370,
    }),
    // Belgium truffle cakes//
    new Cake({
        cakeId: 'bt001',
        name: 'Belgium truffle',
        brandId : 'vsnnsk',
        category: 'tf',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 380,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 380,
    }),
    new Cake({
        cakeId: 'bt002',
        name: 'Belgium truffle',
        brandId : 'vsnnsk',
        category: 'tf',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 400,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 400,
    }),
    new Cake({
        cakeId: 'bt003',
        name: 'Belgium truffle',
        brandId : 'vsnnsk',
        category: 'tf',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 390,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 390,
    }),
    //Chocolate chip cakes
    new Cake({
        cakeId: 'cc001',
        name: 'Chocolate chips',
        brandId : 'vsnnsk',
        category: 'ch',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 390,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 390,
    }),
    new Cake({
        cakeId: 'cc002',
        name: 'Chocolate chips',
        brandId : 'vsnnsk',
        category: 'ch',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 380,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 380,
    }),
    new Cake({
        cakeId: 'cc003',
        name: 'Chocolate chips',
        brandId : 'vsnnsk',
        category: 'ch',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 390,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 390,
    }),
    new Cake({
        cakeId: 'cc005',
        name: 'Chocolate chips',
        brandId : 'vsnnsk',
        category: 'ch',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 390,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 390,
    }),
    //Chocolate kitkat cakes
    new Cake({
        cakeId: 'ck001',
        name: 'Chocolate kitkat',
        brandId : 'vsnnsk',
        category: 'ch',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 400,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 400,
    }),
    new Cake({
        cakeId: 'ck002',
        name: 'Chocolate kitkat',
        brandId : 'vsnnsk',
        category: 'ch',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 400,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 400,
    }),
    new Cake({
        cakeId: 'ck006',
        name: 'Chocolate kitkat',
        brandId : 'vsnnsk',
        category: 'ch',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 390,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 390,
    }),
    new Cake({
        cakeId: 'ck007',
        name: 'Chocolate kitkat',
        brandId : 'vsnnsk',
        category: 'ch',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 400,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 400,
    }),
    //chocolate truufle cakes
    new Cake({
        cakeId: 'ct001',
        name: 'Chocolate truffle',
        brandId : 'vsnnsk',
        category: 'tf',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 390,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 390,
    }),
    new Cake({
        cakeId: 'ct002',
        name: 'Chocolate truffle',
        brandId : 'vsnnsk',
        category: 'tf',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 390,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 390,
    }),
    //Dutch truffle cake
    new Cake({
        cakeId: 'dt001',
        name: 'Dutch truffle',
        brandId : 'vsnnsk',
        category: 'tf',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 390,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 390,
    }),
    new Cake({
        cakeId: 'dt002',
        name: 'Dutch truffle',
        brandId : 'vsnnsk',
        category: 'tf',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 390,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 390,
    }),
    //Fruit cake
    new Cake({
        cakeId: 'fc002',
        name: 'Vanilla Fruit cake',
        brandId : 'vsnnsk',
        category: 'fc',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 390,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 390,
    }),
    new Cake({
        cakeId: 'fc003',
        name: 'vanilla Fruit cake',
        brandId : 'vsnnsk',
        category: 'fc',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 380,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 380,
    }),
    new Cake({
        cakeId: 'fc005',
        name: 'Fruit cake',
        brandId : 'vsnnsk',
        category: 'fc',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 370,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 370,
    }),
    new Cake({
        cakeId: 'fc009',
        name: 'Fruit cake',
        brandId : 'vsnnsk',
        category: 'fc',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 380,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 380,
    }),
    //Ferrero rocher cakes
    // new Cake({
    //     cakeId: 'fr001',
    //     name: 'Ferrero rocher',
    //     brandId : 'vsnnsk',
    //     category: 'fr',
    //     availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
    //     halfKgPrice: 500,
    //     maker : 'Redgini',
    //     minWtCost : 0.5 * 2 * 480,
    // }),
    // new Cake({
    //     cakeId: 'fr004',
    //     name: 'Ferrero rocher',
    //     brandId : 'vsnnsk',
    //     category: 'fr',
    //     availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
    //     halfKgPrice: 510,
    //     maker : 'Redgini',
    //     minWtCost : 0.5 * 2 * 490,
    // }),
    // new Cake({
    //     cakeId: 'fr006',
    //     name: 'Ferrero rocher',
    //     brandId : 'vsnnsk',
    //     category: 'fr',
    //     availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
    //     halfKgPrice: 500,
    //     maker : 'Redgini',
    //     minWtCost : 0.5 * 2 * 480,
    // }),
    // new Cake({
    //     cakeId: 'fr009',
    //     name: 'Ferrero rocher',
    //     brandId : 'vsnnsk',
    //     category: 'fr',
    //     availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
    //     halfKgPrice: 520,
    //     maker : 'Redgini',
    //     minWtCost : 0.5 * 2 * 500,
    // }),
    // new Cake({
    //     cakeId: 'fr013',
    //     name: 'Ferrero rocher',
    //     brandId : 'vsnnsk',
    //     category: 'fr',
    //     availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
    //     halfKgPrice: 510,
    //     maker : 'Redgini',
    //     minWtCost : 0.5 * 2 * 480,
    // }),
    //Chocolate oreo cake
    new Cake({
        cakeId: 'or001',
        name: 'Chocolate oreo',
        brandId : 'vsnnsk',
        category: 'or',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 390,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 390,
    }),
    new Cake({
        cakeId: 'or003',
        name: 'Chocolate oreo',
        brandId : 'vsnnsk',
        category: 'or',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 390,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 390,
    }),
    new Cake({
        cakeId: 'or005',
        name: 'Chocolate oreo',
        brandId : 'vsnnsk',
        category: 'or',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 400,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 400,
    }),
    new Cake({
        cakeId: 'or006',
        name: 'Chocolate oreo',
        brandId : 'vsnnsk',
        category: 'or',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 390,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 390,
    }),
    new Cake({
        cakeId: 'or007',
        name: 'Chocolate oreo',
        brandId : 'vsnnsk',
        category: 'or',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 390,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 390,
    }),
    new Cake({
        cakeId: 'or008',
        name: 'Chocolate oreo',
        brandId : 'vsnnsk',
        category: 'or',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 390,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 390,
    }),
    new Cake({
        cakeId: 'or010',
        name: 'Chocolate oreo',
        brandId : 'vsnnsk',
        category: 'or',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 380,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 380,
    }),
    new Cake({
        cakeId: 'or013',
        name: 'Chocolate oreo',
        brandId : 'vsnnsk',
        category: 'or',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 390,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 390,
    }),
    new Cake({
        cakeId: 'or018',
        name: 'Chocolate oreo',
        brandId : 'vsnnsk',
        category: 'or',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 390,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 390,
    }),
    //Chocolate royal
    new Cake({
        cakeId: 'rc001',
        name: 'Chocolate royal',
        brandId : 'vsnnsk',
        category: 'ch',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 400,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 400,
    }),
    new Cake({
        cakeId: 'rc004',
        name: 'Chocolate royal',
        brandId : 'vsnnsk',
        category: 'ch',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 390,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 390,
    }),
    new Cake({
        cakeId: 'rc006',
        name: 'Chocolate royal',
        brandId : 'vsnnsk',
        category: 'ch',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 400,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 400,
    }),
    new Cake({
        cakeId: 'rc008',
        name: 'Chocolate royal',
        brandId : 'vsnnsk',
        category: 'ch',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 400,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 400,
    }),
    new Cake({
        cakeId: 'rc010',
        name: 'Chocolate royal',
        brandId : 'vsnnsk',
        category: 'ch',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 400,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 400,
    }),
    new Cake({
        cakeId: 'rc013',
        name: 'Chocolate royal',
        brandId : 'vsnnsk',
        category: 'ch',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 400,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 400,
    }),
    new Cake({
        cakeId: 'rc016',
        name: 'Chocolate royal',
        brandId : 'vsnnsk',
        category: 'ch',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 390,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 390,
    }),
    //Red velvet cake
    // new Cake({
    //     cakeId: 'rv001',
    //     name: 'Red velvet',
    //     brandId : 'vsnnsk',
    //     category: 'rv',
    //     availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
    //     halfKgPrice: 390,
    //     maker : 'Redgini',
    //     minWtCost : 0.5 * 2 * 390,
    // }),
    // new Cake({
    //     cakeId: 'rv002',
    //     name: 'Red velvet',
    //     brandId : 'vsnnsk',
    //     category: 'rv',
    //     availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
    //     halfKgPrice: 400,
    //     maker : 'Redgini',
    //     minWtCost : 0.5 * 2 * 400,
    // }),
    // new Cake({
    //     cakeId: 'rv005',
    //     name: 'Red velvet',
    //     brandId : 'vsnnsk',
    //     category: 'rv',
    //     availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
    //     halfKgPrice: 400,
    //     maker : 'Redgini',
    //     minWtCost : 0.5 * 2 * 400,
    // }),
    // new Cake({
    //     cakeId: 'rv010',
    //     name: 'Red velvet | heart',
    //     brandId : 'vsnnsk',
    //     category: 'rv',
    //     availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
    //     halfKgPrice: 420,
    //     maker : 'Redgini',
    //     minWtCost : 0.5 * 2 * 420,
    // }),
    //Pineapple cakes
    new Cake({
        cakeId: 'pa001',
        name: 'Pineapple cake',
        brandId : 'vsnnsk',
        category: 'pa',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 390,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 390,
    }),
    new Cake({
        cakeId: 'pa002',
        name: 'Pineapple cake',
        brandId : 'vsnnsk',
        category: 'pa',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 390,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 390,
    }),
    new Cake({
        cakeId: 'pa003',
        name: 'Pineapple cake',
        brandId : 'vsnnsk',
        category: 'pa',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 390,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 390,
    }),
    //Strawberry vanilla
    new Cake({
        cakeId: 'sv002',
        name: 'Strawberry vanilla',
        brandId : 'vsnnsk',
        category: 'sv',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 400,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 400,
    }),
    new Cake({
        cakeId: 'sv004',
        name: 'Strawberry vanilla',
        brandId : 'vsnnsk',
        category: 'sv',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 390,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 390,
    }),
    new Cake({
        cakeId: 'sv006',
        name: 'Strawberry vanilla',
        brandId : 'vsnnsk',
        category: 'sv',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 390,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 390,
    }),
    //White forest
    new Cake({
        cakeId: 'wf002',
        name: 'White forest',
        brandId : 'vsnnsk',
        category: 'wf',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 400,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 400,
    }),
    new Cake({
        cakeId: 'wf004',
        name: 'White forest',
        brandId : 'vsnnsk',
        category: 'wf',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 380,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 380,
    }),
    new Cake({
        cakeId: 'wf005',
        name: 'White forest',
        brandId : 'vsnnsk',
        category: 'wf',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 390,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 390,
    }),
    // //White hazelnut
    // new Cake({
    //     cakeId: 'wh001',
    //     name: 'White hazelnut',
    //     brandId : 'vsnnsk',
    //     category: 'wh',
    //     availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
    //     halfKgPrice: 360,
    //     maker : 'Redgini',
    //     minWtCost : 0.5 * 2 * 360,
    // }),
    //ameya purohit cakes
    new Cake({
        cakeId: 'bf002',
        name: 'Black forest',
        brandId : 'ampnsk',
        category: 'bf',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 400,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 400,
    }),
    new Cake({
        cakeId: 'bf004',
        name: 'Black forest',
        brandId : 'ampnsk',
        category: 'bf',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 400,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 400,
    }),
    new Cake({
        cakeId: 'bf005',
        name: 'Black forest',
        brandId : 'ampnsk',
        category: 'bf',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 400,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 400,
    }),
    new Cake({
        cakeId: 'bf008',
        name: 'Black forest',
        brandId : 'ampnsk',    
        category: 'bf',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 400,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 400,
    }),
    new Cake({
        cakeId: 'bf011',
        name: 'Black forest',
        brandId : 'ampnsk',
        category: 'bf',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 400,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 400,
    }),
    new Cake({
        cakeId: 'bf013',
        name: 'Black forest',
        brandId : 'ampnsk',
        category: 'bf',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 400,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 400,
    }),
    new Cake({
        cakeId: 'bf015',
        name: 'Black forest',
        brandId : 'ampnsk',
        category: 'bf',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 400,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 400,
    }),
    new Cake({
        cakeId: 'bf016',
        name: 'Black forest',
        brandId : 'ampnsk',
        category: 'bf',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 400,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 400,
    }),
    new Cake({
        cakeId: 'bf017',
        name: 'Black forest',
        brandId : 'ampnsk',
        category: 'bf',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 400,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 400,
    }),
    // Buttercotch cakes//
    new Cake({
        cakeId: 'bs001',
        name: 'ButterScotch',
        brandId : 'ampnsk',
        category: 'bs',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 360,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 360,
    }),
    new Cake({
        cakeId: 'bs002',
        name: 'ButterScotch',
        brandId : 'ampnsk',
        category: 'bs',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 360,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 360,
    }),
    new Cake({
        cakeId: 'bs003',
        name: 'ButterScotch',
        brandId : 'ampnsk',
        category: 'bs',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 360,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 360,
    }),
    new Cake({
        cakeId: 'bs005',
        name: 'ButterScotch',
        brandId : 'ampnsk',
        category: 'bs',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 360,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 360,
    }),
    new Cake({
        cakeId: 'bs006',
        name: 'ButterScotch',
        brandId : 'ampnsk',
        category: 'bs',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 360,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 360,
    }),
    new Cake({
        cakeId: 'bs007',
        name: 'ButterScotch',
        brandId : 'ampnsk',
        category: 'bs',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 360,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 360,
    }),
    new Cake({
        cakeId: 'bs008',
        name: 'ButterScotch',
        brandId : 'ampnsk',
        category: 'bs',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 360,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 360,
    }),
    new Cake({
        cakeId: 'bs009',
        name: 'ButterScotch',
        brandId : 'ampnsk',
        category: 'bs',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 360,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 360,
    }),
    // Belgium truffle cakes//
    // new Cake({
    //     cakeId: 'bt001',
    //     name: 'Belgium truffle',
    //     brandId : 'ampnsk',
    //     category: 'tf',
    //     availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
    //     halfKgPrice: 370,
    //     maker : 'Redgini',
    //     minWtCost : 0.5 * 2 * 370,
    // }),
    // new Cake({
    //     cakeId: 'bt002',
    //     name: 'Belgium truffle',
    //     brandId : 'ampnsk',
    //     category: 'tf',
    //     availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
    //     halfKgPrice: 400,
    //     maker : 'Redgini',
    //     minWtCost : 0.5 * 2 * 400,
    // }),
    // new Cake({
    //     cakeId: 'bt003',
    //     name: 'Belgium truffle',
    //     brandId : 'ampnsk',
    //     category: 'tf',
    //     availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
    //     halfKgPrice: 380,
    //     maker : 'Redgini',
    //     minWtCost : 0.5 * 2 * 380,
    // }),
    //Chocolate chip cakes
    new Cake({
        cakeId: 'cc001',
        name: 'Chocolate chips',
        brandId : 'ampnsk',
        category: 'ch',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 380,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 380,
    }),
    new Cake({
        cakeId: 'cc002',
        name: 'Chocolate chips',
        brandId : 'ampnsk',
        category: 'ch',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 380,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 380,
    }),
    new Cake({
        cakeId: 'cc003',
        name: 'Chocolate chips',
        brandId : 'ampnsk',
        category: 'ch',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 380,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 380,
    }),
    new Cake({
        cakeId: 'cc005',
        name: 'Chocolate chips',
        brandId : 'ampnsk',
        category: 'ch',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 380,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 380,
    }),
    //Chocolate kitkat cakes
    // new Cake({
    //     cakeId: 'ck001',
    //     name: 'Chocolate kitkat',
    //     brandId : 'ampnsk',
    //     category: 'ch',
    //     availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
    //     halfKgPrice: 390,
    //     maker : 'Redgini',
    //     minWtCost : 0.5 * 2 * 390,
    // }),
    // new Cake({
    //     cakeId: 'ck002',
    //     name: 'Chocolate kitkat',
    //     brandId : 'ampnsk',
    //     category: 'ch',
    //     availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
    //     halfKgPrice: 390,
    //     maker : 'Redgini',
    //     minWtCost : 0.5 * 2 * 390,
    // }),
    // new Cake({
    //     cakeId: 'ck006',
    //     name: 'Chocolate kitkat',
    //     brandId : 'ampnsk',
    //     category: 'ch',
    //     availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
    //     halfKgPrice: 370,
    //     maker : 'Redgini',
    //     minWtCost : 0.5 * 2 * 370,
    // }),
    // new Cake({
    //     cakeId: 'ck007',
    //     name: 'Chocolate kitkat',
    //     brandId : 'ampnsk',
    //     category: 'ch',
    //     availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
    //     halfKgPrice: 390,
    //     maker : 'Redgini',
    //     minWtCost : 0.5 * 2 * 390,
    // }),
    //chocolate trufle cakes
    new Cake({
        cakeId: 'ct001',
        name: 'Chocolate truffle',
        brandId : 'ampnsk',
        category: 'tf',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 400,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 400,
    }),
    new Cake({
        cakeId: 'ct002',
        name: 'Chocolate truffle',
        brandId : 'ampnsk',
        category: 'tf',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 400,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 400,
    }),
    //Dutch truffle cake
    new Cake({
        cakeId: 'dt001',
        name: 'Dutch truffle',
        brandId : 'ampnsk',
        category: 'tf',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 400,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 400,
    }),
    new Cake({
        cakeId: 'dt002',
        name: 'Dutch truffle',
        brandId : 'ampnsk',
        category: 'tf',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 400,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 400,
    }),
    //Fruit cake
    new Cake({
        cakeId: 'fc002',
        name: 'Vanilla Fruit cake',
        brandId : 'ampnsk',
        category: 'fc',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 400,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 400,
    }),
    new Cake({
        cakeId: 'fc003',
        name: 'vanilla Fruit cake',
        brandId : 'ampnsk',
        category: 'fc',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 400,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 400,
    }),
    new Cake({
        cakeId: 'fc005',
        name: 'Fruit cake',
        brandId : 'ampnsk',
        category: 'fc',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 400,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 400,
    }),
    new Cake({
        cakeId: 'fc009',
        name: 'Fruit cake',
        brandId : 'ampnsk',
        category: 'fc',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 400,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 400,
    }),
    //Ferrero rocher cakes
    new Cake({
        cakeId: 'fr001',
        name: 'Ferrero rocher',
        brandId : 'ampnsk',
        category: 'fr',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 500,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 500,
    }),
    new Cake({
        cakeId: 'fr004',
        name: 'Ferrero rocher',
        brandId : 'ampnsk',
        category: 'fr',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 500,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 500,
    }),
    new Cake({
        cakeId: 'fr006',
        name: 'Ferrero rocher',
        brandId : 'ampnsk',
        category: 'fr',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 500,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 500,
    }),
    new Cake({
        cakeId: 'fr009',
        name: 'Ferrero rocher',
        brandId : 'ampnsk',
        category: 'fr',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 500,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 500,
    }),
    new Cake({
        cakeId: 'fr013',
        name: 'Ferrero rocher',
        brandId : 'ampnsk',
        category: 'fr',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 500,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 500,
    }),
    //Chocolate oreo cake
    // new Cake({
    //     cakeId: 'or001',
    //     name: 'Chocolate oreo',
    //     brandId : 'ampnsk',
    //     category: 'or',
    //     availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
    //     halfKgPrice: 370,
    //     maker : 'Redgini',
    //     minWtCost : 0.5 * 2 * 370,
    // }),
    // new Cake({
    //     cakeId: 'or003',
    //     name: 'Chocolate oreo',
    //     brandId : 'ampnsk',
    //     category: 'or',
    //     availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
    //     halfKgPrice: 380,
    //     maker : 'Redgini',
    //     minWtCost : 0.5 * 2 * 380,
    // }),
    // new Cake({
    //     cakeId: 'or005',
    //     name: 'Chocolate oreo',
    //     brandId : 'ampnsk',
    //     category: 'or',
    //     availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
    //     halfKgPrice: 380,
    //     maker : 'Redgini',
    //     minWtCost : 0.5 * 2 * 380,
    // }),
    // new Cake({
    //     cakeId: 'or006',
    //     name: 'Chocolate oreo',
    //     brandId : 'ampnsk',
    //     category: 'or',
    //     availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
    //     halfKgPrice: 370,
    //     maker : 'Redgini',
    //     minWtCost : 0.5 * 2 * 370,
    // }),
    // new Cake({
    //     cakeId: 'or007',
    //     name: 'Chocolate oreo',
    //     brandId : 'ampnsk',
    //     category: 'or',
    //     availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
    //     halfKgPrice: 360,
    //     maker : 'Redgini',
    //     minWtCost : 0.5 * 2 * 360,
    // }),
    // new Cake({
    //     cakeId: 'or008',
    //     name: 'Chocolate oreo',
    //     brandId : 'ampnsk',
    //     category: 'or',
    //     availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
    //     halfKgPrice: 370,
    //     maker : 'Redgini',
    //     minWtCost : 0.5 * 2 * 370,
    // }),
    // new Cake({
    //     cakeId: 'or010',
    //     name: 'Chocolate oreo',
    //     brandId : 'ampnsk',
    //     category: 'or',
    //     availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
    //     halfKgPrice: 370,
    //     maker : 'Redgini',
    //     minWtCost : 0.5 * 2 * 370,
    // }),
    // new Cake({
    //     cakeId: 'or013',
    //     name: 'Chocolate oreo',
    //     brandId : 'ampnsk',
    //     category: 'or',
    //     availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
    //     halfKgPrice: 370,
    //     maker : 'Redgini',
    //     minWtCost : 0.5 * 2 * 370,
    // }),
    // new Cake({
    //     cakeId: 'or018',
    //     name: 'Chocolate oreo',
    //     brandId : 'ampnsk',
    //     category: 'or',
    //     availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
    //     halfKgPrice: 370,
    //     maker : 'Redgini',
    //     minWtCost : 0.5 * 2 * 370,
    // }),
    //Chocolate royal
    new Cake({
        cakeId: 'rc001',
        name: 'Chocolate royal',
        brandId : 'ampnsk',
        category: 'ch',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 380,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 380,
    }),
    new Cake({
        cakeId: 'rc004',
        name: 'Chocolate royal',
        brandId : 'ampnsk',
        category: 'ch',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 380,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 380,
    }),
    new Cake({
        cakeId: 'rc006',
        name: 'Chocolate royal',
        brandId : 'ampnsk',
        category: 'ch',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 380,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 380,
    }),
    new Cake({
        cakeId: 'rc008',
        name: 'Chocolate royal',
        brandId : 'ampnsk',
        category: 'ch',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 380,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 380,
    }),
    new Cake({
        cakeId: 'rc010',
        name: 'Chocolate royal',
        brandId : 'ampnsk',
        category: 'ch',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 380,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 380,
    }),
    new Cake({
        cakeId: 'rc013',
        name: 'Chocolate royal',
        brandId : 'ampnsk',
        category: 'ch',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 380,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 380,
    }),
    new Cake({
        cakeId: 'rc016',
        name: 'Chocolate royal',
        brandId : 'ampnsk',
        category: 'ch',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 380,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 380,
    }),
    //Red velvet cake
    new Cake({
        cakeId: 'rv001',
        name: 'Red velvet',
        brandId : 'ampnsk',
        category: 'rv',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 400,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 400,
    }),
    new Cake({
        cakeId: 'rv002',
        name: 'Red velvet',
        brandId : 'ampnsk',
        category: 'rv',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 400,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 400,
    }),
    new Cake({
        cakeId: 'rv005',
        name: 'Red velvet',
        brandId : 'ampnsk',
        category: 'rv',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 400,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 400,
    }),
    new Cake({
        cakeId: 'rv010',
        name: 'Red velvet | heart',
        brandId : 'ampnsk',
        category: 'rv',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 400,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 400,
    }),
    //Pineapple cakes
    new Cake({
        cakeId: 'pa001',
        name: 'Pineapple cake',
        brandId : 'ampnsk',
        category: 'pa',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 325,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 325,
    }),
    new Cake({
        cakeId: 'pa002',
        name: 'Pineapple cake',
        brandId : 'ampnsk',
        category: 'pa',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 325,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 325,
    }),
    new Cake({
        cakeId: 'pa003',
        name: 'Pineapple cake',
        brandId : 'ampnsk',
        category: 'pa',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 325,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 325,
    }),
    //Strawberry vanilla
    // new Cake({
    //     cakeId: 'sv002',
    //     name: 'Strawberry vanilla',
    //     brandId : 'ampnsk',
    //     category: 'sv',
    //     availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
    //     halfKgPrice: 360,
    //     maker : 'Redgini',
    //     minWtCost : 0.5 * 2 * 360,
    // }),
    // new Cake({
    //     cakeId: 'sv004',
    //     name: 'Strawberry vanilla',
    //     brandId : 'ampnsk',
    //     category: 'sv',
    //     availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
    //     halfKgPrice: 380,
    //     maker : 'Redgini',
    //     minWtCost : 0.5 * 2 * 380,
    // }),
    // new Cake({
    //     cakeId: 'sv006',
    //     name: 'Strawberry vanilla',
    //     brandId : 'ampnsk',
    //     category: 'sv',
    //     availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
    //     halfKgPrice: 370,
    //     maker : 'Redgini',
    //     minWtCost : 0.5 * 2 * 370,
    // }),
    //White forest
    new Cake({
        cakeId: 'wf002',
        name: 'White forest',
        brandId : 'ampnsk',
        category: 'wf',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 400,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 400,
    }),
    new Cake({
        cakeId: 'wf004',
        name: 'White forest',
        brandId : 'ampnsk',
        category: 'wf',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 400,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 400,
    }),
    new Cake({
        cakeId: 'wf005',
        name: 'White forest',
        brandId : 'ampnsk',
        category: 'wf',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 400,
        maker : 'Redgini',
        minWtCost : 0.5 * 2 * 400,
    }),
    //White hazelnut
    // new Cake({
    //     cakeId: 'wh001',
    //     name: 'White hazelnut',
    //     brandId : 'ampnsk',
    //     category: 'wh',
    //     availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
    //     halfKgPrice: 400,
    //     maker : 'Redgini',
    //     minWtCost : 0.5 * 2 * 360,
    // }),
    //Designer and fondant cakes
    new Cake({
        cakeId: 'sw_designer001',
        name: 'Theme cake (chocolate)',
        brandId : 'hsbnsk',
        category: 'designer_fondant',
        availableWeights: [1.0, 1.5, 2.0, 2.5, 3.0,4.0,5.0],
        halfKgPrice: 750,
        maker : 'Sweet wonders - Harsha balwani',
        minWtCost : 1.0 * 2 * 750,
    }),
    new Cake({
        cakeId: 'sw_designer002',
        name: 'Mininie mouse cake',
        brandId : 'hsbnsk',
        category: 'designer_fondant',
        availableWeights: [1.0, 1.5, 2.0, 2.5, 3.0,4.0,5.0],
        halfKgPrice: 600,
        maker : 'Sweet wonders - Harsha balwani',
        minWtCost : 1.0 * 2 * 600,
    }),
    new Cake({
        cakeId: 'sw_designer003',
        name: 'Shirt theme',
        brandId : 'hsbnsk',
        category: 'designer_fondant',
        availableWeights: [2.5, 3.0, 3.5, 4.0, 5.0],
        halfKgPrice: 834,
        maker : 'Sweet wonders - Harsha balwani',
        minWtCost : 2.5 * 2 * 834,
    }),
    new Cake({
        cakeId: 'sw_designer004',
        name: 'Mininie mouse cake',
        brandId : 'hsbnsk',
        category: 'designer_fondant',
        availableWeights: [1.0, 1.5, 2.0, 2.5, 3.0,4.0,5.0],
        halfKgPrice: 750,
        maker : 'Sweet wonders - Harsha balwani',
        minWtCost : 1.0 * 2 * 750,
    }),
    new Cake({
        cakeId: 'sw_designer005',
        name: 'Kitkat theme',
        brandId : 'hsbnsk',
        category: 'designer_fondant',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 500,
        maker : 'Sweet wonders - Harsha balwani',
        minWtCost : 0.5 * 2 * 500,
    }),
    new Cake({
        cakeId: 'sw_designer006',
        name: 'Princess theme(chocolate)',
        brandId : 'hsbnsk',
        category: 'designer_fondant',
        availableWeights: [3.0,3.5,4.0,4.5,5.0],
        halfKgPrice: 584,
        maker : 'Sweet wonders - Harsha balwani',
        minWtCost : (3.0 * 2 * 584)-4,
    }),
    new Cake({
        cakeId: 'sw_designer007',
        name: 'Wedding cake',
        brandId : 'hsbnsk',
        category: 'designer_fondant',
        availableWeights: [5.0,6.0,7.0],
        halfKgPrice: 700,
        maker : 'Sweet wonders - Harsha balwani',
        minWtCost : 5.0 * 2 * 700,
    }),
    new Cake({
        cakeId: 'sw_designer008',
        name: 'Anniversary theme',
        brandId : 'hsbnsk',
        category: 'designer_fondant',
        availableWeights: [3.0,4.0,5.0],
        halfKgPrice: 584,
        maker : 'Sweet wonders - Harsha balwani',
        minWtCost : (3.0 * 2 * 584)-4,
    }),
    new Cake({
        cakeId: 'sw_designer009',
        name: 'Baby shower cake(chocolate)',
        brandId : 'hsbnsk',
        category: 'designer_fondant',
        availableWeights: [3.0,4.0,5.0],
        halfKgPrice: 584,
        maker : 'Sweet wonders - Harsha balwani',
        minWtCost : (3.0 * 2 * 584)-4,
    }),
    new Cake({
        cakeId: 'sw_designer010',
        name: 'Disco theme',
        brandId : 'hsbnsk',
        category: 'designer_fondant',
        availableWeights: [5.0,6.0,7.0],
        halfKgPrice: 600,
        maker : 'Sweet wonders - Harsha balwani',
        minWtCost : 5.0 * 2 * 600,
    }),
    new Cake({
        cakeId: 'sw_designer011',
        name: 'Jungle theme',
        brandId : 'hsbnsk',
        category: 'designer_fondant',
        availableWeights: [3.0,4.0,5.0],
        halfKgPrice: 584,
        maker : 'Sweet wonders - Harsha balwani',
        minWtCost : (3.0 * 2 * 584)-4,
    }),
    new Cake({
        cakeId: 'sw_designer012',
        name: 'Wedding cake',
        brandId : 'hsbnsk',
        category: 'designer_fondant',
        availableWeights: [3.0,4.0,5.0],
        halfKgPrice: 667,
        maker : 'Sweet wonders - Harsha balwani',
        minWtCost : (3.0 * 2 * 667)-2,
    }),
    new Cake({
        cakeId: 'sw_designer013',
        name: 'Gems cake',
        brandId : 'hsbnsk',
        category: 'designer_fondant',
        availableWeights: [1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 750,
        maker : 'Sweet wonders - Harsha balwani',
        minWtCost : 1.0 * 2 * 750,
    }),
    new Cake({
        cakeId: 'sw_designer014',
        name: 'Birthday cake',
        brandId : 'hsbnsk',
        category: 'designer_fondant',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 1000,
        maker : 'Sweet wonders - Harsha balwani',
        minWtCost : 0.5 * 2 * 1000,
    }),
    new Cake({
        cakeId: 'sw_designer015',
        name: 'Hot wheels theme',
        brandId : 'hsbnsk',
        category: 'designer_fondant',
        availableWeights: [1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 900,
        maker : 'Sweet wonders - Harsha balwani',
        minWtCost : 1.0 * 2 * 900,
    }),
    new Cake({
        cakeId: 'sw_designer016',
        name: 'Couple theme',
        brandId : 'hsbnsk',
        category: 'designer_fondant',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 1200,
        maker : 'Sweet wonders - Harsha balwani',
        minWtCost : 0.5 * 2 * 1200,
    }),
    new Cake({
        cakeId: 'sw_designer017',
        name: 'Anniversary theme',
        brandId : 'hsbnsk',
        category: 'designer_fondant',
        availableWeights: [2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 500,
        maker : 'Sweet wonders - Harsha balwani',
        minWtCost : 2.0 * 2 * 500,
    }),
    new Cake({
        cakeId: 'sw_designer018',
        name: 'Heart theme',
        brandId : 'hsbnsk',
        category: 'designer_fondant',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 600,
        maker : 'Sweet wonders - Harsha balwani',
        minWtCost : 0.5 * 2 * 600,
    }),
    new Cake({
        cakeId: 'sw_designer019',
        name: 'Wedding cake',
        brandId : 'hsbnsk',
        category: 'designer_fondant',
        availableWeights: [6.0,7.0,8.0],
        halfKgPrice: 584,
        maker : 'Sweet wonders - Harsha balwani',
        minWtCost : (6.0 * 2 * 584)-8,
    }),
    new Cake({
        cakeId: 'sw_designer020',
        name: 'Doctor theme',
        brandId : 'hsbnsk',
        category: 'designer_fondant',
        availableWeights: [1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 900,
        maker : 'Sweet wonders - Harsha balwani',
        minWtCost : 1.0 * 2 * 900,
    }),
    new Cake({
        cakeId: 'sw_designer021',
        name: 'Crown cake',
        brandId : 'hsbnsk',
        category: 'designer_fondant',
        availableWeights: [1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 750,
        maker : 'Sweet wonders - Harsha balwani',
        minWtCost : 1.0 * 2 * 750,
    }),
    new Cake({
        cakeId: 'sw_designer022',
        name: 'Kids theme',
        brandId : 'hsbnsk',
        category: 'designer_fondant',
        availableWeights: [1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 750,
        maker : 'Sweet wonders - Harsha balwani',
        minWtCost : 1.0 * 2 * 750,
    }),
    new Cake({
        cakeId: 'sw_designer023',
        name: 'Football jersey theme',
        brandId : 'hsbnsk',
        category: 'designer_fondant',
        availableWeights: [2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 500,
        maker : 'Sweet wonders - Harsha balwani',
        minWtCost : 2.0 * 2 * 500,
    }),
    new Cake({
        cakeId: 'sw_designer024',
        name: 'Maggie theme',
        brandId : 'hsbnsk',
        category: 'designer_fondant',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 1000,
        maker : 'Sweet wonders - Harsha balwani',
        minWtCost : 0.5 * 2 * 1000,
    }),
    new Cake({
        cakeId: 'sw_designer025',
        name: 'Motu patlu cake',
        brandId : 'hsbnsk',
        category: 'designer_fondant',
        availableWeights: [1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 750,
        maker : 'Sweet wonders - Harsha balwani',
        minWtCost : 1.0 * 2 * 750,
    }),
    new Cake({
        cakeId: 'sw_designer026',
        name: 'Makeup kit theme',
        brandId : 'hsbnsk',
        category: 'designer_fondant',
        availableWeights: [1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 900,
        maker : 'Sweet wonders - Harsha balwani',
        minWtCost : 1.0 * 2 * 900,
    }),
    new Cake({
        cakeId: 'sw_designer027',
        name: 'Lion theme',
        brandId : 'hsbnsk',
        category: 'designer_fondant',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 800,
        maker : 'Sweet wonders - Harsha balwani',
        minWtCost : 0.5 * 2 * 800,
    }),
    new Cake({
        cakeId: 'sw_designer028',
        name: 'Camera theme',
        brandId : 'hsbnsk',
        category: 'designer_fondant',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 1000,
        maker : 'Sweet wonders - Harsha balwani',
        minWtCost : 0.5 * 2 * 1000,
    }),
    new Cake({
        cakeId: 'sw_designer029',
        name: 'Shirt theme',
        brandId : 'hsbnsk',
        category: 'designer_fondant',
        availableWeights: [1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 600,
        maker : 'Sweet wonders - Harsha balwani',
        minWtCost : 1.0 * 2 * 600,
    }),
    new Cake({
        cakeId: 'sw_designer030',
        name: 'Flower theme',
        brandId : 'hsbnsk',
        category: 'designer_fondant',
        availableWeights: [1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 750,
        maker : 'Sweet wonders - Harsha balwani',
        minWtCost : 1.0 * 2 * 750,
    }),
    new Cake({
        cakeId: 'sw_designer031',
        name: 'Beer bottle theme',
        brandId : 'hsbnsk',
        category: 'designer_fondant',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 900,
        maker : 'Sweet wonders - Harsha balwani',
        minWtCost : 0.5 * 2 * 900,
    }),
    new Cake({
        cakeId: 'sw_designer032',
        name: 'Basketball theme',
        brandId : 'hsbnsk',
        category: 'designer_fondant',
        availableWeights: [2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 625,
        maker : 'Sweet wonders - Harsha balwani',
        minWtCost : 2.0 * 2 * 625,
    }),
    new Cake({
        cakeId: 'sw_designer033',
        name: 'Original bottle(as you wish) theme',
        brandId : 'hsbnsk',
        category: 'designer_fondant',
        availableWeights: [1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 600,
        maker : 'Sweet wonders - Harsha balwani',
        minWtCost : 1.0 * 2 * 600,
    }),
    new Cake({
        cakeId: 'sw_designer034',
        name: 'Drums theme',
        brandId : 'hsbnsk',
        category: 'designer_fondant',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 1000,
        maker : 'Sweet wonders - Harsha balwani',
        minWtCost : 0.5 * 2 * 1000,
    }),
    new Cake({
        cakeId: 'sw_designer035',
        name: 'Flower theme',
        brandId : 'hsbnsk',
        category: 'designer_fondant',
        availableWeights: [1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 600,
        maker : 'Sweet wonders - Harsha balwani',
        minWtCost : 1.0 * 2 * 600,
    }),
    new Cake({
        cakeId: 'sw_designer036',
        name: 'Chips theme',
        brandId : 'hsbnsk',
        category: 'designer_fondant',
        availableWeights: [1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 750,
        maker : 'Sweet wonders - Harsha balwani',
        minWtCost : 1.0 * 2 * 750,
    }),
    new Cake({
        cakeId: 'sw_designer037',
        name: 'Batman theme',
        brandId : 'hsbnsk',
        category: 'designer_fondant',
        availableWeights: [3.0,4.0,5.0],
        halfKgPrice: 467,
        maker : 'Sweet wonders - Harsha balwani',
        minWtCost : (3.0 * 2 * 467)-2,
    }),
    new Cake({
        cakeId: 'sw_designer038',
        name: 'Car theme',
        brandId : 'hsbnsk',
        category: 'designer_fondant',
        availableWeights: [4.0,5.0,6.0,7.0],
        halfKgPrice: 562.5,
        maker : 'Sweet wonders - Harsha balwani',
        minWtCost : 4.0 * 2 * 562.5,
    }),
    new Cake({
        cakeId: 'sw_designer039',
        name: 'Missal theme',
        brandId : 'hsbnsk',
        category: 'designer_fondant',
        availableWeights: [1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 900,
        maker : 'Sweet wonders - Harsha balwani',
        minWtCost : 1.0 * 2 * 900,
    }),
    new Cake({
        cakeId: 'sw_designer040',
        name: 'Roulette theme',
        brandId : 'hsbnsk',
        category: 'designer_fondant',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 1200,
        maker : 'Sweet wonders - Harsha balwani',
        minWtCost : 0.5 * 2 * 1200,
    }),
    new Cake({
        cakeId: 'sw_designer041',
        name: 'Lady theme',
        brandId : 'hsbnsk',
        category: 'designer_fondant',
        availableWeights: [1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 750,
        maker : 'Sweet wonders - Harsha balwani',
        minWtCost : 1.0 * 2 * 750,
    }),
    new Cake({
        cakeId: 'sw_designer042',
        name: 'Birthday theme',
        brandId : 'hsbnsk',
        category: 'designer_fondant',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 1000,
        maker : 'Sweet wonders - Harsha balwani',
        minWtCost : 0.5 * 2 * 1000,
    }),
    new Cake({
        cakeId: 'sw_designer043',
        name: 'Doremon theme',
        brandId : 'hsbnsk',
        category: 'designer_fondant',
        availableWeights: [2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 450,
        maker : 'Sweet wonders - Harsha balwani',
        minWtCost : 2.0 * 2 * 450,
    }),
    new Cake({
        cakeId: 'sw_designer044',
        name: 'Missal theme',
        brandId : 'hsbnsk',
        category: 'designer_fondant',
        availableWeights: [1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 900,
        maker : 'Sweet wonders - Harsha balwani',
        minWtCost : 1.0 * 2 * 900,
    }),
    new Cake({
        cakeId: 'sw_designer045',
        name: 'Rabbit theme',
        brandId : 'hsbnsk',
        category: 'designer_fondant',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 800,
        maker : 'Sweet wonders - Harsha balwani',
        minWtCost : 0.5 * 2 * 800,
    }),
    new Cake({
        cakeId: 'sw_designer046',
        name: 'Birthday theme',
        brandId : 'hsbnsk',
        category: 'designer_fondant',
        availableWeights: [3.0,4.0,5.0],
        halfKgPrice: 584,
        maker : 'Sweet wonders - Harsha balwani',
        minWtCost : (3.0 * 2 * 584)-4,
    }),
    new Cake({
        cakeId: 'sw_designer047',
        name: 'Laptop/Computer theme',
        brandId : 'hsbnsk',
        category: 'designer_fondant',
        availableWeights: [1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 900,
        maker : 'Sweet wonders - Harsha balwani',
        minWtCost : 1.0 * 2 * 900,
    }),
    new Cake({
        cakeId: 'sw_designer048',
        name: 'Couple special',
        brandId : 'hsbnsk',
        category: 'designer_fondant',
        availableWeights: [2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 700,
        maker : 'Sweet wonders - Harsha balwani',
        minWtCost : 2.0 * 2 * 700,
    }),
    new Cake({
        cakeId: 'sw_designer049',
        name: 'Beer theme',
        brandId : 'hsbnsk',
        category: 'designer_fondant',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 1000,
        maker : 'Sweet wonders - Harsha balwani',
        minWtCost : 0.5 * 2 * 1000,
    }),
    new Cake({
        cakeId: 'sw_designer050',
        name: 'Car theme',
        brandId : 'hsbnsk',
        category: 'designer_fondant',
        availableWeights: [1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 900,
        maker : 'Sweet wonders - Harsha balwani',
        minWtCost : 1.0 * 2 * 900,
    }),
    new Cake({
        cakeId: 'sw_designer051',
        name: 'Couple special',
        brandId : 'hsbnsk',
        category: 'designer_fondant',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 1000,
        maker : 'Sweet wonders - Harsha balwani',
        minWtCost : 0.5 * 2 * 1000,
    }),
    new Cake({
        cakeId: 'sw_designer052',
        name: 'Gems theme',
        brandId : 'hsbnsk',
        category: 'designer_fondant',
        availableWeights: [1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 750,
        maker : 'Sweet wonders - Harsha balwani',
        minWtCost : 1.0 * 2 * 750,
    }),
    new Cake({
        cakeId: 'sw_designer053',
        name: 'Wedding theme',
        brandId : 'hsbnsk',
        category: 'designer_fondant',
        availableWeights: [3.0,4.0,5.0],
        halfKgPrice: 550,
        maker : 'Sweet wonders - Harsha balwani',
        minWtCost : 3.0 * 2 * 550,
    }),
    new Cake({
        cakeId: 'sw_designer054',
        name: 'Original bottle(as you wish) theme',
        brandId : 'hsbnsk',
        category: 'designer_fondant',
        availableWeights: [1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 600,
        maker : 'Sweet wonders - Harsha balwani',
        minWtCost : 1.0 * 2 * 600,
    }),
    new Cake({
        cakeId: 'sw_designer055',
        name: 'Drum theme',
        brandId : 'hsbnsk',
        category: 'designer_fondant',
        availableWeights: [1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 900,
        maker : 'Sweet wonders - Harsha balwani',
        minWtCost : 1.0 * 2 * 900,
    }),
    new Cake({
        cakeId: 'sw_designer056',
        name: 'Wedding theme',
        brandId : 'hsbnsk',
        category: 'designer_fondant',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 550,
        maker : 'Sweet wonders - Harsha balwani',
        minWtCost : 0.5 * 2 * 550,
    }),
    new Cake({
        cakeId: 'sw_designer057',
        name: 'Wedding theme',
        brandId : 'hsbnsk',
        category: 'designer_fondant',
        availableWeights: [3.0,4.0,5.0],
        halfKgPrice: 500,
        maker : 'Sweet wonders - Harsha balwani',
        minWtCost : 3.0 * 2 * 500,
    }),
    new Cake({
        cakeId: 'sw_designer058',
        name: 'Wedding theme',
        brandId : 'hsbnsk',
        category: 'designer_fondant',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 550,
        maker : 'Sweet wonders - Harsha balwani',
        minWtCost : 0.5 * 2 * 550,
    }),
    new Cake({
        cakeId: 'sw_designer059',
        name: 'Wedding theme',
        brandId : 'hsbnsk',
        category: 'designer_fondant',
        availableWeights: [3.0,4.0,5.0],
        halfKgPrice: 550,
        maker : 'Sweet wonders - Harsha balwani',
        minWtCost : 3.0 * 2 * 550,
    }),
    new Cake({
        cakeId: 'sw_designer060',
        name: 'Lady theme',
        brandId : 'hsbnsk',
        category: 'designer_fondant',
        availableWeights: [1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 900,
        maker : 'Sweet wonders - Harsha balwani',
        minWtCost : 1.0 * 2 * 900,
    }),
    new Cake({
        cakeId: 'sw_designer061',
        name: 'Shirt theme',
        brandId : 'hsbnsk',
        category: 'designer_fondant',
        availableWeights: [1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 750,
        maker : 'Sweet wonders - Harsha balwani',
        minWtCost : 1.0 * 2 * 750,
    }),
    new Cake({
        cakeId: 'sw_designer062',
        name: 'Aeroplane theme',
        brandId : 'hsbnsk',
        category: 'designer_fondant',
        availableWeights: [3.0,4.0,5.0],
        halfKgPrice: 584,
        maker : 'Sweet wonders - Harsha balwani',
        minWtCost : (3.0 * 2 * 584)-4,
    }),
    new Cake({
        cakeId: 'sw_designer063',
        name: 'Flower basket',
        brandId : 'hsbnsk',
        category: 'designer_fondant',
        availableWeights: [2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 450,
        maker : 'Sweet wonders - Harsha balwani',
        minWtCost : 2.0 * 2 * 450,
    }),
    new Cake({
        cakeId: 'sw_designer064',
        name: 'Couple special',
        brandId : 'hsbnsk',
        category: 'designer_fondant',
        availableWeights: [1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 600,
        maker : 'Sweet wonders - Harsha balwani',
        minWtCost : 1.0 * 2 * 600,
    }),
    new Cake({
        cakeId: 'sw_designer065',
        name: 'Couple special',
        brandId : 'hsbnsk',
        category: 'designer_fondant',
        availableWeights: [1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 600,
        maker : 'Sweet wonders - Harsha balwani',
        minWtCost : 1.0 * 2 * 600,
    }),
    new Cake({
        cakeId: 'sw_designer066',
        name: 'Wedding theme',
        brandId : 'hsbnsk',
        category: 'designer_fondant',
        availableWeights: [5.0, 6.0,7.0],
        halfKgPrice: 500,
        maker : 'Sweet wonders - Harsha balwani',
        minWtCost : 5.0 * 2 * 500,
    }),
    new Cake({
        cakeId: 'sw_designer067',
        name: 'Football theme',
        brandId : 'hsbnsk',
        category: 'designer_fondant',
        availableWeights: [1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 900,
        maker : 'Sweet wonders - Harsha balwani',
        minWtCost : 1.0 * 2 * 900,
    }),
    new Cake({
        cakeId: 'sw_designer068',
        name: 'Flower theme',
        brandId : 'hsbnsk',
        category: 'designer_fondant',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 600,
        maker : 'Sweet wonders - Harsha balwani',
        minWtCost : 0.5 * 2 * 600,
    }),
    new Cake({
        cakeId: 'sw_designer069',
        name: 'Lady design theme',
        brandId : 'hsbnsk',
        category: 'designer_fondant',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 600,
        maker : 'Sweet wonders - Harsha balwani',
        minWtCost : 0.5 * 2 * 600,
    }),
    new Cake({
        cakeId: 'sw_designer070',
        name: 'Sandal pairs',
        brandId : 'hsbnsk',
        category: 'designer_fondant',
        availableWeights: [1.0,2.0,3.0,4.0,5.0],
        halfKgPrice: 500,
        maker : 'Sweet wonders - Harsha balwani',
        minWtCost : 1.0 * 2 * 500,
    }),
    new Cake({
        cakeId: 'sw_designer071',
        name: 'Wedding rheme',
        brandId : 'hsbnsk',
        category: 'designer_fondant',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 600,
        maker : 'Sweet wonders - Harsha balwani',
        minWtCost : 0.5 * 2 * 600,
    }),
    new Cake({
        cakeId: 'sw_designer072',
        name: 'Sandal theme',
        brandId : 'hsbnsk',
        category: 'designer_fondant',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 500,
        maker : 'Sweet wonders - Harsha balwani',
        minWtCost : 0.5 * 2 * 500,
    }),
    new Cake({
        cakeId: 'sw_designer073',
        name: 'Birthday theme',
        brandId : 'hsbnsk',
        category: 'designer_fondant',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 1200,
        maker : 'Sweet wonders - Harsha balwani',
        minWtCost : 0.5 * 2 * 1200,
    }),
    new Cake({
        cakeId: 'sw_designer074',
        name: 'barbie doll theme',
        brandId : 'hsbnsk',
        category: 'designer_fondant',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 1000,
        maker : 'Sweet wonders - Harsha balwani',
        minWtCost : 0.5 * 2 * 1000,
    }),
    new Cake({
        cakeId: 'sw_designer075',
        name: 'Music theme',
        brandId : 'hsbnsk',
        category: 'designer_fondant',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 800,
        maker : 'Sweet wonders - Harsha balwani',
        minWtCost : 0.5 * 2 * 800,
    }),
    new Cake({
        cakeId: 'sw_designer076',
        name: 'Car theme',
        brandId : 'hsbnsk',
        category: 'designer_fondant',
        availableWeights: [1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 900,
        maker : 'Sweet wonders - Harsha balwani',
        minWtCost : 1.0 * 2 * 900,
    }),
    new Cake({
        cakeId: 'sw_designer077',
        name: 'Birthday theme',
        brandId : 'hsbnsk',
        category: 'designer_fondant',
        availableWeights: [0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0],
        halfKgPrice: 800,
        maker : 'Sweet wonders - Harsha balwani',
        minWtCost : 0.5 * 2 * 800,
    })
];

var done = 0;
for (var i = 0; i < cakes.length; i++) {
    cakes[i].save(function(err, result) {
        done++;
        if (done === cakes.length) {
            exit();
        }
    });
}

function exit() {
    mongoose.disconnect();
}
